version: '3.7'

services:

    app.jvc:
        build:
            dockerfile: .docker/build/Dockerfile
            context: .
        environment:
            DATABASE_HOST: database.jvc
            DATABASE_NAME: ${DATABASE_NAME:-jvc}
            DATABASE_USER: ${DATABASE_USER:-jvc}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_PORT: 3306
            APP_PSEUDO_TO_SEARCH: ${APP_PSEUDO_TO_SEARCH:-}
        networks:
            - database

    database.jvc:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - ./volumes/database/data:/var/lib/mysql
            - ./last_forum.yaml:/app/last_forum.yaml
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: true
            MARIADB_DATABASE: ${DATABASE_NAME:-jvc}
            MARIADB_USER: ${DATABASE_USER:-jvc}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
        networks:
            - database

networks:
    database: